"""Test features of REDcap autogenerated classes.
"""
import pytest
import vbr

# rcap_patient_demographics_full_part_2_v03_demographics


def test_table_name_munge():
    """Test hack for fixing Redcap table names."""
    instance = vbr.tableclasses.RcapPatientDemographicsFullPart2V03Demographics()
    assert "part_2" in instance.__schema__.table_name


def test_class_from_table_name_munge():
    """Class can be retrieved from table name"""
    # Special case
    assert (
        vbr.tableclasses.class_from_table(
            "rcap_patient_demographics_full_part_2_v03_demographics"
        )
        == vbr.tableclasses.redcap.autogenerated.patient_demographics_full_part_2_v03_demographics.RcapPatientDemographicsFullPart2V03Demographics
    )
    # Regular case
    assert (
        vbr.tableclasses.class_from_table("rcap_consented_participant_information")
        == vbr.tableclasses.redcap.autogenerated.consented_participant_information.RcapConsentedParticipantInformation
    )


def test_table_from_class_munge():
    """Table name can be retrieved by class"""
    # Special case
    assert (
        vbr.tableclasses.table_from_class(
            vbr.tableclasses.RcapPatientDemographicsFullPart2V03Demographics
        )
        == "rcap_patient_demographics_full_part_2_v03_demographics"
    )
    # Regular case
    assert (
        vbr.tableclasses.table_from_class(
            vbr.tableclasses.redcap.autogenerated.consented_participant_information.RcapConsentedParticipantInformation
        )
        == "rcap_consented_participant_information"
    )
