"""Autogenerated 2024-09-18T10:32:28.926772 by redcap_classfiles.py
"""

from ....pgrest import *
from ...constants import Constants
from ..rcconstants import REDCapConstants

from ..rcaptable import RcapTable

__all__ = ['RcapBaselineVisitReset']


class RcapBaselineVisitReset(RcapTable):
    """Baseline Visit Reset
    """
    __redcap_form_name = 'baseline_visit_reset'
    baseline_visit_reset_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    baseline_visit_reset_complete = Column(Integer,
                                           ForeignKey('status.status_id'))
    # Collection date of Baseline Forms being reset
    # Field Type: text
    # Choices: N/A
    bvr_visit_date = Column(String, nullable=True, comments=None)
