"""Autogenerated 2024-09-18T10:32:28.849861 by redcap_classfiles.py
"""

from ....pgrest import *
from ...constants import Constants
from ..rcconstants import REDCapConstants

from ..rcaptable import RcapTable

__all__ = ['RcapConsentedParticipantInformation']


class RcapConsentedParticipantInformation(RcapTable):
    """Consented Participant Information
    """
    __redcap_form_name = 'consented_participant_information'
    consented_participant_information_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    consented_participant_information_complete = Column(
        Integer, ForeignKey('status.status_id'))
    # Record ID
    # Field Type: text
    # Choices: N/A
    record_id = Column(String, nullable=True, comments=None)
    # GUID
    # Field Type: text
    # Choices: N/A
    guid = Column(GUID, nullable=True, comments=None)
    # NDA GUID
    # Field Type: text
    # Choices: N/A
    nda_guid = Column(String, nullable=True, comments=None)
    # Screening ID
    # Field Type: text
    # Choices: N/A
    screening_id = Column(String, nullable=True, comments=None)
    # First Name
    # Field Type: text
    # Choices: N/A
    first_name = Column(String, nullable=True, comments=None)
    # Last Name
    # Field Type: text
    # Choices: N/A
    last_name = Column(String, nullable=True, comments=None)
    # Email
    # Field Type: text
    # Choices: N/A
    patient_email = Column(String, nullable=True, comments=None)
    # Mobile Phone
    # Field Type: text
    # Choices: N/A
    mobile_phone_number = Column(String, nullable=True, comments=None)
    # Home Phone
    # Field Type: text
    # Choices: N/A
    home_phone_number = Column(String, nullable=True, comments=None)
    # Preferred Contact method
    # Field Type: radio
    # Choices: 2, E-mail | 1, Text | 0, Mobile/Home
    contact_method = Column(Integer, nullable=True, comments=None)
    # What language do you prefer to use for surveys?Spanish is onl...
    # Field Type: radio
    # Choices: en, English | es, Spanish
    contact_language = Column(String, nullable=True, comments=None)
    # Was this participant reconsented for the June 30, 2022 consen...
    # Field Type: radio
    # Choices: 1, yes - participant has been re-consented | 0, no - participant still needs re-consent
    reconsent06302022 = Column(Boolean, nullable=True, comments=None)
    # August 2021 TACC Server Downtime Notification: Send downtime ...
    # Field Type: radio
    # Choices: 0, No | 1, Yes
    downtime202108 = Column(Boolean, nullable=True, comments=None)
    # August 2021 TACC Server Maintenance Completed Notification: S...
    # Field Type: radio
    # Choices: 0, No | 1, Yes
    maintcomp202108 = Column(Boolean, nullable=True, comments=None)
    # September 2021 TACC Server Downtime Notification: Send downti...
    # Field Type: radio
    # Choices: 0, No | 1, Yes
    downtime202109 = Column(Boolean, nullable=True, comments=None)
    # June 21 2022 TACC Server Downtime Notification: Send downtime...
    # Field Type: radio
    # Choices: 0, No | 1, Yes
    downtime20220621 = Column(Boolean, nullable=True, comments=None)
