"""Autogenerated 2024-09-18T10:32:28.919419 by redcap_classfiles.py
"""

from ....pgrest import *
from ...constants import Constants
from ..rcconstants import REDCapConstants

from ..rcaptable import RcapTable

__all__ = ['RcapCurrentMedicationsV02']


class RcapCurrentMedicationsV02(RcapTable):
    """Current Medications V02
    """
    __redcap_form_name = 'current_medications_v02'
    current_medications_v02_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    current_medications_v02_complete = Column(Integer,
                                              ForeignKey('status.status_id'))
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Yes | 0, No | 3, Unknown
    cmc_medsleepdepr = Column(Integer, nullable=True, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Yes | 0, No | 3, Unknown
    cmc_medhtcd = Column(Integer, nullable=True, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Yes | 0, No | 3, Unknown
    cmc_medhclipids = Column(Integer, nullable=True, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Yes | 0, No | 3, Unknown
    cmc_medseizadhd = Column(Integer, nullable=True, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Yes | 0, No | 3, Unknown
    cmc_medpainopioid = Column(Integer, nullable=True, comments=None)
    # 6. In the past 24 hours have you taken any of the following p...
    # Field Type: radio
    # Choices: 1, Yes | 0, No | 3, Unknown
    cmc_medpainpregabdulo = Column(Integer, nullable=True, comments=None)
    #  6b. NSAIDs (Ibuprofen (Advil, Motrin), naproxyn (Aleve), asp...
    # Field Type: radio
    # Choices: 1, Yes | 0, No | 3, Unknown
    cmc_medpainnsaids = Column(Integer, nullable=True, comments=None)
    #  6c. Acetaminophen (Tylenol)
    # Field Type: radio
    # Choices: 1, Yes | 0, No | 3, Unknown
    cmc_medpaintylenol = Column(Integer, nullable=True, comments=None)
