"""Autogenerated 2021-11-05T15:48:31.955792 by redcap_classfiles.py
"""

from ....pgrest import *
from ...constants import Constants
from ..rcaptable import RcapTable
from ..rcconstants import REDCapConstants

__all__ = ["RcapCurrentMedicationsV02"]


class RcapCurrentMedicationsV02(RcapTable):
    """Current Medications V02"""

    __redcap_form_name = "current_medications_v02"
    current_medications_v02_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    current_medications_v02_complete = Column(Integer, ForeignKey("status.status_id"))
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Yes | 0, No | 3, Unknown
    cmc_medsleepdepr = Column(Integer, nullable=True, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Yes | 0, No | 3, Unknown
    cmc_medhtcd = Column(Integer, nullable=True, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Yes | 0, No | 3, Unknown
    cmc_medhclipids = Column(Integer, nullable=True, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Yes | 0, No | 3, Unknown
    cmc_medseizadhd = Column(Integer, nullable=True, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Yes | 0, No | 3, Unknown
    cmc_medpainopioid = Column(Integer, nullable=True, comments=None)
