"""Autogenerated 2021-10-12T11:54:28.951169 by redcap_classfiles.py
"""

from vbr.pgrest import *
from vbr.tableclasses import Constants
from vbr.pgrest.constraints import Signature

from ..rcconstants import REDCapConstants
from ..rcaptable import RcapTable

__all__ = ['RcapEarlyWithdrawalV04']

class RcapEarlyWithdrawalV04(RcapTable):
    """Early Withdrawal V04
    """
    __redcap_form_name = 'early_withdrawal_v04'
    early_withdrawal_v04_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    early_withdrawal_v04_complete = Column(Integer, ForeignKey('status.status_id'))
    # Date of early termination
    # Field Type: text
    # Choices: N/A
    ewdateterm = Column(String, nullable=True, comments=None)
    # Primary reason for termination
    # Field Type: radio
    # Choices: 1, Subject chose to discontinue the study | 2, Site PI chose to discontinue subject participation | 3, Subject is lost to follow-up, unable to locate | 4, Death
    ewprimaryreason = Column(Integer, nullable=True, comments=None)
    # Reason(s) participant chose to discontinue (may select more t...
    # Field Type: checkbox
    # Choices: 1, Unwilling or unable to perform study-related activities. | 2, Study-related adverse event | 3, Inadequate compensation | 4, COVID-related | 5, Withdrew consent | 6, None given/other (add to notes)
    ewdisreasons = Column(Integer, nullable=True, comments=None)
    # Reason PI chose to discontinue participation
    # Field Type: radio
    # Choices: 1, Subject did not have surgery. | 2, Second procedure scheduled. | 3, Subject unable to perform study-related activities | 4, Adverse event | 5, Other (add to notes)
    ewpireason = Column(Integer, nullable=True, comments=None)
    # Initials of study personnel
    # Field Type: text
    # Choices: N/A
    ewstudypinit = Column(String, nullable=True, comments=None)