"""Autogenerated 2024-09-18T10:32:28.933957 by redcap_classfiles.py
"""

from ....pgrest import *
from ...constants import Constants
from ..rcconstants import REDCapConstants

from ..rcaptable import RcapTable

__all__ = ['RcapEarlyWithdrawalV04']


class RcapEarlyWithdrawalV04(RcapTable):
    """Early Withdrawal V04
    """
    __redcap_form_name = 'early_withdrawal_v04'
    early_withdrawal_v04_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    early_withdrawal_v04_complete = Column(Integer,
                                           ForeignKey('status.status_id'))
    # Date of early termination
    # Field Type: text
    # Choices: N/A
    ewdateterm = Column(String, nullable=True, comments=None)
    # Primary reason for termination
    # Field Type: radio
    # Choices: 1, Subject chose to discontinue the study | 2, Site PI chose to discontinue subject participation | 3, Subject is lost to follow-up, unable to locate | 4, Death
    ewprimaryreason = Column(Integer, nullable=True, comments=None)
    # 2.A. Is the subject asking that their data be removed from th...
    # Field Type: radio
    # Choices: 1, Yes | 0, No
    ewreqdataremoval = Column(Boolean, nullable=True, comments=None)
    # 2.A.ii. Enter any notes here to document that subject asked t...
    # Field Type: notes
    # Choices: N/A
    ewdocdataremovalnote = Column(FreeText, nullable=True, comments=None)
    # Reason(s) participant chose to discontinue (may select more t...
    # Field Type: checkbox
    # Choices: 1, Unwilling or unable to perform study-related activities. | 2, Study-related adverse event | 3, Inadequte compensation | 4, COVID-related | 6, None given/other (add to notes)
    ewdisreasons = Column(Integer, nullable=True, comments=None)
    # Reason PI chose to discontinue participation
    # Field Type: radio
    # Choices: 1, Subject did not have surgery. | 2, Second procedure scheduled. | 3, Subject unable to perform study-related activities | 4, Adverse event | 5, Other (add to notes)
    ewpireason = Column(Integer, nullable=True, comments=None)
    # Initials of study personnel
    # Field Type: text
    # Choices: N/A
    ewstudypinit = Column(String, nullable=True, comments=None)
    # Notes/Comments
    # Field Type: notes
    # Choices: N/A
    ewcomments = Column(FreeText, nullable=True, comments=None)
