"""Autogenerated 2024-09-18T10:32:28.876871 by redcap_classfiles.py
"""

from ....pgrest import *
from ...constants import Constants
from ..rcconstants import REDCapConstants

from ..rcaptable import RcapTable

__all__ = ['RcapFearavoidanceBeliefsQuestionnaireV03Fabq']


class RcapFearavoidanceBeliefsQuestionnaireV03Fabq(RcapTable):
    """Fearavoidance Beliefs Questionnaire V03 Fabq
    """
    __redcap_form_name = 'fearavoidance_beliefs_questionnaire_v03_fabq'
    fearavoidance_beliefs_questionnaire_v03_fabq_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    fearavoidance_beliefs_questionnaire_v03_fabq_complete = Column(
        Integer, ForeignKey('status.status_id'))
    # Physical activity makes my pain worse
    # Field Type: radio
    # Choices: 0, 0 - Completely disagree | 1, 1 | 2, 2 | 3, 3 - Unsure | 4, 4 | 5, 5 | 6, 6 - Completely agree
    fabqphysclactvtywrsscl = Column(Integer, nullable=True, comments=None)
    # Physical activity might harm my knee
    # Field Type: radio
    # Choices: 0, 0 - Completely disagree | 1, 1 | 2, 2 | 3, 3 - Unsure | 4, 4 | 5, 5 | 6, 6 - Completely agree
    fabqphysclactvtybckhrmscl = Column(Integer, nullable=True, comments=None)
    # I should not do physical activities which (might) make my pai...
    # Field Type: radio
    # Choices: 0, 0 - Completely disagree | 1, 1 | 2, 2 | 3, 3 - Unsure | 4, 4 | 5, 5 | 6, 6 - Completely agree
    fabqphysactvtyshldntdoscl = Column(Integer, nullable=True, comments=None)
    # I cannot do physical activities which (might) make my pain worse
    # Field Type: radio
    # Choices: 0, 0 - Completely disagree | 1, 1 | 2, 2 | 3, 3 - Unsure | 4, 4 | 5, 5 | 6, 6 - Completely agree
    fabqphysactvtycnntdoscl = Column(Integer, nullable=True, comments=None)
