"""Autogenerated 2021-09-02T13:30:49.097274 by redcap_classfiles.py
"""

from vbr.pgrest import *
from vbr.tableclasses import Constants
from vbr.pgrest.constraints import Signature

from ..rcconstants import REDCapConstants
from ..rcaptable import RcapTable

__all__ = ['RcapImagingMcc2V01']


class RcapImagingMcc2V01(RcapTable):
    """Imaging Mcc2 V01
    """
    __redcap_form_name = 'imaging_mcc2_v01'
    imaging_mcc2_v01_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    imaging_mcc2_v01_complete = Column(Integer, ForeignKey('status.status_id'))
    # Investigator initials
    # Field Type: text
    # Choices: N/A
    fmricuff_initials = Column(String, nullable=False, comments=None)
    # Verify Patient Name (as entered into scanner console):  Patie...
    # Field Type: text
    # Choices: N/A
    fmripatientname = Column(String, nullable=False, comments=None)
    # fMRI Magnet Name
    # Field Type: radio
    # Choices: 1, Explorer MRI (BIRB) | 2, Discovery MRI (Modular Unit)
    fmri_magnet_name = Column(Integer, nullable=False, comments=None)
    # Cuff pressure contraindicated: [cuffpfmricontraindyn] (From Q...
    # Field Type: descriptive
    # Choices: N/A
    fmri_dt_0 = Column(String, nullable=False, comments=None)
    # Cuff Pressure fMRI: Cuff Pressure to achieve 4/10 pain outsid...
    # Field Type: descriptive
    # Choices: N/A
    fmri_dt_1 = Column(String, nullable=False, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Right | 2, Left
    fmricuffleg = Column(Integer, nullable=False, comments=None)
    # Re-calibration of pressure needed
    # Field Type: radio
    # Choices: 1, Yes | 0, No
    fmricuffcontrarecal = Column(Boolean, nullable=False, comments=None)
    # Calf pressure, contralateral calf, Pressure 2
    # Field Type: text
    # Choices: N/A
    fmricuffcalfpressurerecal = Column(String, nullable=False, comments=None)
    # Calf pressure, contralateral calf, Pressure 2: (double entry)
    # Field Type: text
    # Choices: N/A
    fmricuffcalfpressurerecal2 = Column(String, nullable=False, comments=None)
    # Please enter technologist's quality rating for the T1 scan
    # Field Type: radio
    # Choices: 3, Green - good, Class 3 | 2, Yellow - borderline, Class 2 | 1, Red - unusable, Class 1
    fmricufft1techrating = Column(Integer, nullable=False, comments=None)
    # T1 scan repeated?
    # Field Type: yesno
    # Choices: N/A
    fmricufft1repeated = Column(Boolean, nullable=False, comments=None)
    # Please enter technologist's quality rating for the 2nd T1 scan
    # Field Type: radio
    # Choices: 3, Green - good, Class 3 | 2, Yellow - borderline, Class 2 | 1, Red - unusable, Class 1
    fmricufft1techrating2 = Column(Integer, nullable=False, comments=None)
    # Pain Ratings:   Before first resting fMRI scan
    # Field Type: descriptive
    # Choices: N/A
    fmri_dt_2 = Column(String, nullable=False, comments=None)
    # Surgical site pain
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffrestpainss = Column(Numeric, nullable=False, comments=None)
    # Surgical site pain (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffrestpainss2 = Column(Numeric, nullable=False, comments=None)
    # Body pain
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffrestpainovrall = Column(Numeric, nullable=False, comments=None)
    # Body pain (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffrestpainovrall2 = Column(Numeric, nullable=False, comments=None)
    # After first resting fMRI scan
    # Field Type: descriptive
    # Choices: N/A
    fmri_dt_3 = Column(String, nullable=False, comments=None)
    # Surgical site
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffcurrpainaftfirstscanss = Column(Numeric,
                                            nullable=False,
                                            comments=None)
    # Surgical site (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffcurrpainaftfirstscanss2 = Column(Numeric,
                                             nullable=False,
                                             comments=None)
    # Body pain
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffcurrpainaftfirstscanovrall = Column(Numeric,
                                                nullable=False,
                                                comments=None)
    # Body pain (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffcurrpainaftfirstscanovrall2 = Column(Numeric,
                                                 nullable=False,
                                                 comments=None)
    # Cuff pain
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffcurrpainaftfirstscancuff = Column(Numeric,
                                              nullable=False,
                                              comments=None)
    # Cuff (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffcurrpainaftfirstscancuff2 = Column(Numeric,
                                               nullable=False,
                                               comments=None)
    # After first cuff fMRI scan (personalized cuff pressure): Now ...
    # Field Type: descriptive
    # Choices: N/A
    fmri_dt_6 = Column(String, nullable=False, comments=None)
    # cuff pain beginning
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainbegin = Column(Numeric, nullable=False, comments=None)
    # cuff pain beginning (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainbegin2 = Column(Numeric, nullable=False, comments=None)
    # cuff pain middle
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainmid = Column(Numeric, nullable=False, comments=None)
    # cuff pain middle (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainmid2 = Column(Numeric, nullable=False, comments=None)
    # cuff pain end
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainend = Column(Numeric, nullable=False, comments=None)
    # cuff pain end (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainend2 = Column(Numeric, nullable=False, comments=None)
    # After second cuff fMRI scan (constant 120 mmHg pressure): Now...
    # Field Type: descriptive
    # Choices: N/A
    fmri_dt_7 = Column(String, nullable=False, comments=None)
    # cuff pain beginning
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpaincpbegin = Column(Numeric, nullable=False, comments=None)
    # cuff pain beginning (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpaincpbegin2 = Column(Numeric, nullable=False, comments=None)
    # cuff pain middle
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpaincpmid = Column(Numeric, nullable=False, comments=None)
    # cuff pain middle (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpaincpmid2 = Column(Numeric, nullable=False, comments=None)
    # cuff pain end
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpaincpend = Column(Numeric, nullable=False, comments=None)
    # cuff pain end (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpaincpend2 = Column(Numeric, nullable=False, comments=None)
    # After last resting fMRI scan
    # Field Type: descriptive
    # Choices: N/A
    fmri_dt_8 = Column(String, nullable=False, comments=None)
    # cuff pain beginning
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainrestscanbegin = Column(Numeric, nullable=False, comments=None)
    # cuff pain beginning (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainrestscanbegin2 = Column(Numeric, nullable=False, comments=None)
    # cuff pain middle
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainrestscanmid = Column(Numeric, nullable=False, comments=None)
    # cuff pain middle (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainrestscanmid2 = Column(Numeric, nullable=False, comments=None)
    # cuff pain end
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainrestscanend = Column(Numeric, nullable=False, comments=None)
    # cuff pain end (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainrestscanend2 = Column(Numeric, nullable=False, comments=None)
    # Surgical site pain
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainaftlastscanss = Column(Numeric, nullable=False, comments=None)
    # Surgical site pain (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainaftlastscanss2 = Column(Numeric, nullable=False, comments=None)
    # Body pain
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainaftlastscanany = Column(Numeric, nullable=False, comments=None)
    # Body pain (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    fmricuffpainaftlastscanany2 = Column(Numeric,
                                         nullable=False,
                                         comments=None)
    # Test Completed
    # Field Type: radio
    # Choices: 1, Yes, all scans were completed | 2, Yes, but only the scans indicated below were completed | 0, No, no scans were completed (add reason(s) to notes below)
    fmricuffcompletescl = Column(Integer, nullable=False, comments=None)
    # T1
    # Field Type: yesno
    # Choices: N/A
    fmricufft1yn = Column(Boolean, nullable=False, comments=None)
    # DWI
    # Field Type: yesno
    # Choices: N/A
    fmricuffdwiyn = Column(Boolean, nullable=False, comments=None)
    # 1rst Resting state
    # Field Type: yesno
    # Choices: N/A
    fmricuffrest1yn = Column(Boolean, nullable=False, comments=None)
    # fMRI individualized pressure
    # Field Type: yesno
    # Choices: N/A
    fmricuffipyn = Column(Boolean, nullable=False, comments=None)
    # fMRI standard pressure
    # Field Type: yesno
    # Choices: N/A
    fmricuffspyn = Column(Boolean, nullable=False, comments=None)
    # 2nd Resting state
    # Field Type: yesno
    # Choices: N/A
    fmricuffrest2yn = Column(Boolean, nullable=False, comments=None)
    # Dicom files uploaded to TACC
    # Field Type: yesno
    # Choices: N/A
    fmricuffdicuploaded = Column(Boolean, nullable=False, comments=None)
    # Upload date/time
    # Field Type: text
    # Choices: N/A
    fmricuffdicupdate = Column(String, nullable=False, comments=None)
