"""Autogenerated 2021-09-02T13:30:48.986723 by redcap_classfiles.py
"""

from vbr.pgrest import *
from vbr.tableclasses import Constants
from vbr.pgrest.constraints import Signature

from ..rcconstants import REDCapConstants
from ..rcaptable import RcapTable

__all__ = ['RcapPainsleepDurationSleepIi']


class RcapPainsleepDurationSleepIi(RcapTable):
    """Painsleep Duration Sleep Ii
    """
    __redcap_form_name = 'painsleep_duration_sleep_ii'
    painsleep_duration_sleep_ii_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    painsleep_duration_sleep_ii_complete = Column(
        Integer, ForeignKey('status.status_id'))
    #      hours minutes    During the past month, on average, how ...
    # Field Type: descriptive
    # Choices: N/A
    sleepnight_dt_1 = Column(String, nullable=False, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: text
    # Choices: N/A
    sleepnighthourmindurhrs = Column(String, nullable=False, comments=None)
    # and
    # Field Type: text
    # Choices: N/A
    sleepnighthourmindurmins = Column(String, nullable=False, comments=None)
