"""Autogenerated 2021-10-12T11:27:30.964689 by redcap_classfiles.py
"""

from vbr.pgrest import *
from vbr.tableclasses import Constants
from vbr.pgrest.constraints import Signature

from ..rcconstants import REDCapConstants
from ..rcaptable import RcapTable

__all__ = ['RcapPatientEncounters']

class RcapPatientEncounters(RcapTable):
    """Patient Encounters
    """
    __redcap_form_name = 'patient_encounters'
    patient_encounters_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    patient_encounters_complete = Column(Integer, ForeignKey('status.status_id'))
    # Enter date and time of this patient encounter
    # Field Type: text
    # Choices: N/A
    pe_datetime = Column(String, nullable=False, comments=None)
    # Staff member initials
    # Field Type: text
    # Choices: N/A
    pe_staff_init = Column(String, nullable=False, comments=None)