"""Autogenerated 2021-10-12T11:54:28.808651 by redcap_classfiles.py
"""

from vbr.pgrest import *
from vbr.tableclasses import Constants
from vbr.pgrest.constraints import Signature

from ..rcconstants import REDCapConstants
from ..rcaptable import RcapTable

__all__ = ['RcapPatientGlobalImpressionOfChangePgic']

class RcapPatientGlobalImpressionOfChangePgic(RcapTable):
    """Patient Global Impression Of Change Pgic
    """
    __redcap_form_name = 'patient_global_impression_of_change_pgic'
    patient_global_impression_of_change_pgic_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    patient_global_impression_of_change_pgic_complete = Column(Integer, ForeignKey('status.status_id'))
    # Since the start of the study (treatment), my overall pain is ...
    # Field Type: radio
    # Choices: 0, Very much improved | 1, Much improved | 2, Minimally improved | 3, No change | 4, Minimally worse | 5, Much worse | 6, Very much worse
    pgicsymptomchangestatval = Column(Integer, nullable=True, comments=None)