"""Autogenerated 2024-09-18T10:32:28.858504 by redcap_classfiles.py
"""

from ....pgrest import *
from ...constants import Constants
from ..rcconstants import REDCapConstants

from ..rcaptable import RcapTable

__all__ = ['RcapPatientGlobalImpressionOfChangePgic']


class RcapPatientGlobalImpressionOfChangePgic(RcapTable):
    """Patient Global Impression Of Change Pgic
    """
    __redcap_form_name = 'patient_global_impression_of_change_pgic'
    patient_global_impression_of_change_pgic_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    patient_global_impression_of_change_pgic_complete = Column(
        Integer, ForeignKey('status.status_id'))
    # Since the start of the study (treatment), my overall pain is ...
    # Field Type: radio
    # Choices: 0, Very much improved | 1, Much improved | 2, Minimally improved | 3, No change | 4, Minimally worse | 5, Much worse | 6, Very much worse
    pgicsymptomchangestatval = Column(Integer, nullable=True, comments=None)
