"""Autogenerated 2024-09-18T10:32:28.852496 by redcap_classfiles.py
"""

from ....pgrest import *
from ...constants import Constants
from ..rcconstants import REDCapConstants

from ..rcaptable import RcapTable

__all__ = ['RcapPostconsentStudyPlanCrfV06']


class RcapPostconsentStudyPlanCrfV06(RcapTable):
    """Postconsent Study Plan Crf V06
    """
    __redcap_form_name = 'postconsent_study_plan_crf_v06'
    postconsent_study_plan_crf_v06_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    postconsent_study_plan_crf_v06_complete = Column(
        Integer, ForeignKey('status.status_id'))
    # Completed informed consent
    # Field Type: radio
    # Choices: 1, yes | 0, no
    sp_inclinfconsdone = Column(Boolean, nullable=True, comments=None)
    # Stated willingness to comply with all base study activities f...
    # Field Type: radio
    # Choices: 1, yes | 0, no
    sp_inclcomply = Column(Boolean, nullable=True, comments=None)
    # Between the ages of 18 to < 85 years.
    # Field Type: radio
    # Choices: 1, yes | 0, no
    sp_inclage1884 = Column(Boolean, nullable=True, comments=None)
    # Individuals diagnosed with knee osteoarthritis scheduled to u...
    # Field Type: radio
    # Choices: 1, yes | 0, no
    sp_inclsurg = Column(Boolean, nullable=True, comments=None)
    # Patient has undergone prior thoracic surgery within 3-months.
    # Field Type: radio
    # Choices: 1, yes | 0, no
    sp_exclprevbilthorpro = Column(Boolean, nullable=True, comments=None)
    # Patient undergoing:  a bilateral thoracic procedure. another ...
    # Field Type: radio
    # Choices: 1, yes | 0, no
    sp_exclothmajorsurg = Column(Boolean, nullable=True, comments=None)
    # Patient unable to provide informed consent; or unable to read...
    # Field Type: radio
    # Choices: 1, yes | 0, no
    sp_exclnoreadspkenglish = Column(Boolean, nullable=True, comments=None)
    # Planned surgical incision site
    # Field Type: radio
    # Choices: 1, Right chest | 2, Left chest
    sp_plansurgincissite = Column(Integer, nullable=True, comments=None)
    # Is the participant's thoracic surgery being performed to addr...
    # Field Type: radio
    # Choices: 1, yes | 0, no
    sp_surgcardiac = Column(Boolean, nullable=True, comments=None)
    # MRI compatibility screening
    # Field Type: radio
    # Choices: 1, Pt has MR imaging contraindications, exclude from study | 2, MRI compatibility screen incomplete, need additional information from patient | 3, MRI screen complete, needs follow-up to determine compatibility by investigator | 4, Complete, cleared for imaging (no known contraindications)
    sp_mricompatscr = Column(Integer, nullable=True, comments=None)
    # Additional Comments
    # Field Type: notes
    # Choices: N/A
    sp_comments = Column(FreeText, nullable=True, comments=None)
    # Site where data collection will be performed
    # Field Type: radio
    # Choices: 1, U of Michigan | 2, Wayne State | 3, Spectrum Health
    sp_data_site = Column(Integer, nullable=True, comments=None)
    # Confirm Surgery Date
    # Field Type: text
    # Choices: N/A
    sp_surg_date = Column(String, nullable=True, comments=None)
    # V1 (Pre-Op) date
    # Field Type: text
    # Choices: N/A
    sp_v1_preop_date = Column(String, nullable=True, comments=None)
    # V1 (Pre-Op) time
    # Field Type: text
    # Choices: N/A
    sp_v1_preop_time = Column(String, nullable=True, comments=None)
    # V1 (Pre-Op) time AM/PM
    # Field Type: dropdown
    # Choices: AM, AM | PM, PM
    sp_v1_preop_time_ampm = Column(String, nullable=True, comments=None)
    # V2 (~6 week Follow-up) date
    # Field Type: text
    # Choices: N/A
    sp_v2_6wk_date = Column(String, nullable=True, comments=None)
    # V3 (~3 month Follow-up) date
    # Field Type: text
    # Choices: N/A
    sp_v3_3mo_date = Column(String, nullable=True, comments=None)
    # Please indicate how you would like to receive Pre-Visit surveys
    # Field Type: radio
    # Choices: 1, E-mail with survey link | 2, Text message with survey link (need smart phone) | 3, In-person (provide paper version)
    sp_previsit_survey_pref = Column(Integer, nullable=True, comments=None)
    # Please indicate how you would like to receive Daily Trajector...
    # Field Type: radio
    # Choices: 1, E-mail | 2, Text message with link, take via browser (smart phone) | 3, Text message, take survey via SMS (flip phone) | 4, Automated voice option | 5, In-person (provide paper version)
    sp_daily_survey_pref = Column(Integer, nullable=True, comments=None)
    # Patient undergoing knee replacement for an inflammatory arthr...
    # Field Type: radio
    # Choices: 1, yes | 0, no
    sp_exclarthkneerep = Column(Boolean, nullable=True, comments=None)
    # Patient undergoing revision surgery with an infectious diagno...
    # Field Type: radio
    # Choices: 1, yes | 0, no
    sp_exclinfdxjoint = Column(Boolean, nullable=True, comments=None)
    # Patient undergoing:  bilateral knee replacements, planned sta...
    # Field Type: radio
    # Choices: 1, yes | 0, no
    sp_exclbilkneerep = Column(Boolean, nullable=True, comments=None)
    # Confirm surgical incision site
    # Field Type: radio
    # Choices: 1, Right Knee | 2, Left Knee
    sp_surgsite = Column(Integer, nullable=True, comments=None)
    # Indicate site where imaging will be done
    # Field Type: radio
    # Choices: 1, University of Illinois at Chicago | 2, Rush University Medical Center
    sp_imaging_site = Column(Integer, nullable=True, comments=None)
    # Send electronic surveys to this participant? If YES, electron...
    # Field Type: radio
    # Choices: 1, Yes | 0, No
    sp_assess_remote = Column(Boolean, nullable=True, comments=None)
