"""Autogenerated 2024-09-18T10:32:28.879876 by redcap_classfiles.py
"""

from ....pgrest import *
from ...constants import Constants
from ..rcconstants import REDCapConstants

from ..rcaptable import RcapTable

__all__ = ['RcapPromisSfV20EmotionalSupport6A']


class RcapPromisSfV20EmotionalSupport6A(RcapTable):
    """Promis Sf V20 Emotional Support 6A
    """
    __redcap_form_name = 'promis_sf_v20_emotional_support_6a'
    promis_sf_v20_emotional_support_6a_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    promis_sf_v20_emotional_support_6a_complete = Column(
        Integer, ForeignKey('status.status_id'))
    # I have someone who will listen to me when I need to talk
    # Field Type: radio
    # Choices: 1, Never | 2, Rarely | 3, Sometimes | 4, Usually | 5, Always
    essfsomeonelistenscl = Column(Integer, nullable=True, comments=None)
    # I have someone to confide in or talk to about myself or my pr...
    # Field Type: radio
    # Choices: 1, Never | 2, Rarely | 3, Sometimes | 4, Usually | 5, Always
    essfsomeoneconfidescl = Column(Integer, nullable=True, comments=None)
    # I have someone who makes me feel appreciated
    # Field Type: radio
    # Choices: 1, Never | 2, Rarely | 3, Sometimes | 4, Usually | 5, Always
    essffeelappreciatscl = Column(Integer, nullable=True, comments=None)
    # I have someone to talk with when I have a bad day
    # Field Type: radio
    # Choices: 1, Never | 2, Rarely | 3, Sometimes | 4, Usually | 5, Always
    essftalkbaddayscl = Column(Integer, nullable=True, comments=None)
    # I have someone who understands my problems
    # Field Type: radio
    # Choices: 1, Never | 2, Rarely | 3, Sometimes | 4, Usually | 5, Always
    essfunderstandprobscl = Column(Integer, nullable=True, comments=None)
    # I have someone I trust to talk with about my feelings
    # Field Type: radio
    # Choices: 1, Never | 2, Rarely | 3, Sometimes | 4, Usually | 5, Always
    essftalkfeelingsscl = Column(Integer, nullable=True, comments=None)
