"""Autogenerated 2021-11-05T05:03:30.353024 by redcap_classfiles.py
"""

from ....pgrest import *
from ...constants import Constants
from ..rcaptable import RcapTable
from ..rcconstants import REDCapConstants

__all__ = ["RcapPromisSfV10SleepDisturbance6ASleepI"]


class RcapPromisSfV10SleepDisturbance6ASleepI(RcapTable):
    """Promis Sf V10 Sleep Disturbance 6A Sleep I"""

    __redcap_form_name = "promis_sf_v10_sleep_disturbance_6a_sleep_i"
    promis_sf_v10_sleep_disturbance_6a_sleep_i_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    promis_sf_v10_sleep_disturbance_6a_sleep_i_complete = Column(
        Integer, ForeignKey("status.status_id")
    )
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 5, Not at all | 4, A little bit | 3, Somewhat | 2, Quite a bit | 1, Very much
    promissleepwasrefreshscl = Column(Integer, nullable=True, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Not at all | 2, A little bit | 3, Somewhat | 4, Quite a bit | 5, Very much
    promisproblemwithslpscl = Column(Integer, nullable=True, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Not at all | 2, A little bit | 3, Somewhat | 4, Quite a bit | 5, Very much
    promisdifficltfallaslpscl = Column(Integer, nullable=True, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Not at all | 2, A little bit | 3, Somewhat | 4, Quite a bit | 5, Very much
    promisslpwasrestlessscl = Column(Integer, nullable=True, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 1, Not at all | 2, A little bit | 3, Somewhat | 4, Quite a bit | 5, Very much
    promistryhardgettoslpscl = Column(Integer, nullable=True, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: radio
    # Choices: 5, Very poor | 4, Poor | 3, Fair | 2, Good | 1, Very good
    promissleepqualityscl = Column(Integer, nullable=True, comments=None)
