"""Autogenerated 2021-10-12T11:27:30.862902 by redcap_classfiles.py
"""

from vbr.pgrest import *
from vbr.tableclasses import Constants
from vbr.pgrest.constraints import Signature

from ..rcconstants import REDCapConstants
from ..rcaptable import RcapTable

__all__ = ['RcapPromisSfV20InformationalSupport6A']

class RcapPromisSfV20InformationalSupport6A(RcapTable):
    """Promis Sf V20 Informational Support 6A
    """
    __redcap_form_name = 'promis_sf_v20_informational_support_6a'
    promis_sf_v20_informational_support_6a_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    promis_sf_v20_informational_support_6a_complete = Column(Integer, ForeignKey('status.status_id'))
    # Do you have someone to help you if you are confined to bed?
    # Field Type: radio
    # Choices: 1, Never | 2, Rarely | 3, Sometimes | 4, Usually | 5, Always
    issfconfinedbedscl = Column(Integer, nullable=False, comments=None)
    # Do you have someone to take you to the doctor if you need it?
    # Field Type: radio
    # Choices: 1, Never | 2, Rarely | 3, Sometimes | 4, Usually | 5, Always
    issfdoctorvisitscl = Column(Integer, nullable=False, comments=None)
    # Do you have someone to help you with your daily chores if you...
    # Field Type: radio
    # Choices: 1, Never | 2, Rarely | 3, Sometimes | 4, Usually | 5, Always
    issfchoreshelpscl = Column(Integer, nullable=False, comments=None)
    # Do you have someone to run errands if you need it?
    # Field Type: radio
    # Choices: 1, Never | 2, Rarely | 3, Sometimes | 4, Usually | 5, Always
    issferrandshelpscl = Column(Integer, nullable=False, comments=None)
    # Do you have someone to prepare your meals if you are unable t...
    # Field Type: radio
    # Choices: 1, Never | 2, Rarely | 3, Sometimes | 4, Usually | 5, Always
    issfmealprepscl = Column(Integer, nullable=False, comments=None)
    # Do you have someone to take over all of your responsibilities...
    # Field Type: radio
    # Choices: 1, Never | 2, Rarely | 3, Sometimes | 4, Usually | 5, Always
    issfresponsiblescl = Column(Integer, nullable=False, comments=None)