"""Autogenerated 2021-09-02T13:30:49.056731 by redcap_classfiles.py
"""

from vbr.pgrest import *
from vbr.tableclasses import Constants
from vbr.pgrest.constraints import Signature

from ..rcconstants import REDCapConstants
from ..rcaptable import RcapTable

__all__ = ['RcapQstMcc1V03']


class RcapQstMcc1V03(RcapTable):
    """Qst Mcc1 V03
    """
    __redcap_form_name = 'qst_mcc1_v03'
    qst_mcc1_v03_id = Constants.SERIAL_PRIMARY_KEY_COLUMN
    qst_mcc1_v03_complete = Column(Integer, ForeignKey('status.status_id'))
    # Pressure Pain Threshold (PPT) (continued) Chest PPTs. Double ...
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_1 = Column(String, nullable=False, comments=None)
    # Location of greater knee pain(index site)
    # Field Type: radio
    # Choices: 1, medial | 2, lateral | 3, equal
    pptpainlocation = Column(Integer, nullable=False, comments=None)
    # (If equal, default to medial joint line for testing)
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_2 = Column(String, nullable=False, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_3 = Column(String, nullable=False, comments=None)
    # Rep 1
    # Field Type: text
    # Choices: N/A
    pptremote1val = Column(String, nullable=False, comments=None)
    # Rep 1: (double entry)
    # Field Type: text
    # Choices: N/A
    pptremote1val1 = Column(String, nullable=False, comments=None)
    # Rep 1 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_rep1 = Column(String, nullable=False, comments=None)
    # Rep 2
    # Field Type: text
    # Choices: N/A
    pptremote2val = Column(String, nullable=False, comments=None)
    # Rep 2: (double entry)
    # Field Type: text
    # Choices: N/A
    pptremote2val1 = Column(String, nullable=False, comments=None)
    # Rep 2 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_rep2 = Column(String, nullable=False, comments=None)
    # Rep 3
    # Field Type: text
    # Choices: N/A
    pptremote3val = Column(String, nullable=False, comments=None)
    # Rep 3:  (double entry)
    # Field Type: text
    # Choices: N/A
    pptremote3val1 = Column(String, nullable=False, comments=None)
    # Rep 3 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_rep3 = Column(String, nullable=False, comments=None)
    # Index site (med/lat joint line)
    # Field Type: descriptive
    # Choices: N/A
    qst_dt_4 = Column(String, nullable=False, comments=None)
    # Rep 1
    # Field Type: text
    # Choices: N/A
    pptindex1val = Column(String, nullable=False, comments=None)
    # Rep 1: (double entry)
    # Field Type: text
    # Choices: N/A
    pptindex1val1 = Column(String, nullable=False, comments=None)
    # Rep 1 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_irep1 = Column(String, nullable=False, comments=None)
    # Rep 2
    # Field Type: text
    # Choices: N/A
    pptindex2val = Column(String, nullable=False, comments=None)
    # Rep 2: (double entry)
    # Field Type: text
    # Choices: N/A
    pptindex2val1 = Column(String, nullable=False, comments=None)
    # Rep 2 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_irep2 = Column(String, nullable=False, comments=None)
    # Rep 3
    # Field Type: text
    # Choices: N/A
    pptindex3val = Column(String, nullable=False, comments=None)
    # Rep 3: (double entry)
    # Field Type: text
    # Choices: N/A
    pptindex3val1 = Column(String, nullable=False, comments=None)
    # Rep 3 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_irep3 = Column(String, nullable=False, comments=None)
    # Test completed?
    # Field Type: radio
    # Choices: 1, yes, both sites | 2, only remote (shoulder) | 3, only index (chest) | 0, no, neither site
    pptcompleteyn = Column(Integer, nullable=False, comments=None)
    # Temporal Summation:
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_5 = Column(String, nullable=False, comments=None)
    # Initial Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsrep1initialpainrem = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsrep1initialpainrem_d = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating entries do not match! Please check your e...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_ipr = Column(String, nullable=False, comments=None)
    # Final Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsrep1finalpainrem = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsrep1finalpainrem_d = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating entries do not match! Please check your ent...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_fpr = Column(String, nullable=False, comments=None)
    # Initial Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsrep2initialpainrem = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsrep2initialpainrem_d = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating entries do not match! Please check your e...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_index_ipr_2 = Column(String, nullable=False, comments=None)
    # Final Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsrep2finalpainrem = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsrep2finalpainrem_d = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating entries do not match! Please check your ent...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_index_fpr_2 = Column(String, nullable=False, comments=None)
    # Initial Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsinitialpainremsclr3 = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsinitialpainremscl1r3 = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsfinalpainremsclr3 = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsfinalpainremscl1r3 = Column(Numeric, nullable=False, comments=None)
    # Remote After-sensations: 	15 sec
    # Field Type: text
    # Choices: N/A
    tsfinalpainremafts15 = Column(String, nullable=False, comments=None)
    # (single entry)	30 sec
    # Field Type: text
    # Choices: N/A
    tsfinalpainremafts30 = Column(String, nullable=False, comments=None)
    # Initial Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsrep1initialpainindex = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsrep1initialpainindex_d = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating entries do not match! Please check your e...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_index_ipr = Column(String, nullable=False, comments=None)
    # Final Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsrep1finalpainindex = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsrep1finalpainindex_d = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating entries do not match! Please check your ent...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_index_fpr = Column(String, nullable=False, comments=None)
    # Initial Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsinitialpainindexsclr2 = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsinitialpainindexscl1r2 = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsfinalpainindexsclr2 = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsfinalpainindexscl1r2 = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsinitialpainindexsclr3 = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsinitialpainindexscl1r3 = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsfinalpainindexsclr3 = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsfinalpainindexscl1r3 = Column(Numeric, nullable=False, comments=None)
    # Index After-sensations: 	15 sec
    # Field Type: text
    # Choices: N/A
    tsfinalpainindafts15 = Column(String, nullable=False, comments=None)
    # (single entry)	30 sec
    # Field Type: text
    # Choices: N/A
    tsfinalpainindafts30 = Column(String, nullable=False, comments=None)
    # Test completed?
    # Field Type: radio
    # Choices: 1, yes, at least 1 repetition for both sites | 2, only remote (shoulder) | 3, only index (chest) | 0, no, neither site
    tscompleted = Column(Integer, nullable=False, comments=None)
    # Conditioned Pain Modulation:
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_6 = Column(String, nullable=False, comments=None)
    # Confirm water temp 10 deg C (+/-1 deg)
    # Field Type: radio
    # Choices: 1, Yes | 0, No
    cpmcoldwatertempc = Column(Boolean, nullable=False, comments=None)
    # Cold Water Pain Rating at 30 sec
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    cpmcoldwaterpain30sscl = Column(Numeric, nullable=False, comments=None)
    # Cold Water Pain Rating at 30 sec: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    cpmcoldwaterpain30sscl1 = Column(Numeric, nullable=False, comments=None)
    # Cold Water Pain Rating at 60 sec
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    cpmcoldwaterpain60sscl = Column(Numeric, nullable=False, comments=None)
    # Cold Water Pain Rating at 60 sec: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    cpmcoldwaterpain60sscl1 = Column(Numeric, nullable=False, comments=None)
    # Water bath duration?
    # Field Type: radio
    # Choices: 1, Standard range (60sec +/- 5 sec) | 2, Outside of range: < 55sec or > 65 sec
    cpmbathrangeyn = Column(Integer, nullable=False, comments=None)
    # If outside of range, enter time (sec)
    # Field Type: text
    # Choices: N/A
    cpmoutrangetime = Column(String, nullable=False, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: descriptive
    # Choices: N/A
    cpm_dt_4 = Column(String, nullable=False, comments=None)
    # Rep 1
    # Field Type: text
    # Choices: N/A
    cpmppt1val = Column(String, nullable=False, comments=None)
    # Rep 1: (double entry)
    # Field Type: text
    # Choices: N/A
    cpmppt1val1 = Column(String, nullable=False, comments=None)
    # Rep 2
    # Field Type: text
    # Choices: N/A
    cpmppt2val = Column(String, nullable=False, comments=None)
    # Rep 2: (double entry)
    # Field Type: text
    # Choices: N/A
    cpmppt2val1 = Column(String, nullable=False, comments=None)
    # Rep 3
    # Field Type: text
    # Choices: N/A
    cpmppt3val = Column(String, nullable=False, comments=None)
    # Rep 3: (double entry)
    # Field Type: text
    # Choices: N/A
    cpmppt3val1 = Column(String, nullable=False, comments=None)
    # Test Completed
    # Field Type: yesno
    # Choices: N/A
    cpmcompleteyn = Column(Boolean, nullable=False, comments=None)
    # Cuff pressure contraindicated
    # Field Type: radio
    # Choices: 1, Yes | 0, No
    fmricuffcontrayn = Column(Boolean, nullable=False, comments=None)
    # Calf pressure, contralateral calf, Pressure 1
    # Field Type: text
    # Choices: N/A
    fmricuffcalfpressure = Column(String, nullable=False, comments=None)
    # Calf pressure, contralateral calf, Pressure 1: (double entry)
    # Field Type: text
    # Choices: N/A
    fmricuffcalfpressure2 = Column(String, nullable=False, comments=None)
    # Pain Mapping Assessment (PMA)
    # Field Type: descriptive
    # Choices: N/A
    dma_dt1 = Column(String, nullable=False, comments=None)
    # New chest pain since surgery?
    # Field Type: radio
    # Choices: 1, Yes | 0, No
    pmachgchestpainyn = Column(Boolean, nullable=False, comments=None)
    # General region of pain
    # Field Type: radio
    # Choices: 1, Anterior chest | 2, Axillary/lateral | 3, Posterior chest
    pmapainregion = Column(Integer, nullable=False, comments=None)
    # Highest pain location
    # Field Type: radio
    # Choices: 1, T1 | 2, T2 | 3, T3 | 4, T4 | 5, T5 | 6, T6 | 7, T7 | 8, T8 | 9, T9 | 10, T10 | 11, T11 | 12, T12 | 13, Above or below thoracic levels
    pmahighestloc = Column(Integer, nullable=False, comments=None)
    # Lowest pain location
    # Field Type: radio
    # Choices: 1, T1 | 2, T2 | 3, T3 | 4, T4 | 5, T5 | 6, T6 | 7, T7 | 8, T8 | 9, T9 | 10, T10 | 11, T11 | 12, T12 | 13, Above or below thoracic levels
    pmalowestloc = Column(Integer, nullable=False, comments=None)
    # Most painful region
    # Field Type: radio
    # Choices: 1, At the scar | 2, Immediately around the scar (<= 4 cm) | 3, Distant from the scar (> 4 cm)
    pmamostpain = Column(Integer, nullable=False, comments=None)
    # 6. Shoulder PPTsPPTs (in kg, to 2 decimal places; min value 0...
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_4 = Column(String, nullable=False, comments=None)
    # Rep 1
    # Field Type: text
    # Choices: N/A
    pptremoter1val = Column(String, nullable=False, comments=None)
    # Rep 1: (double entry)
    # Field Type: text
    # Choices: N/A
    pptremoter1val_d = Column(String, nullable=False, comments=None)
    # Rep 1 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_rep7 = Column(String, nullable=False, comments=None)
    # Rep 2
    # Field Type: text
    # Choices: N/A
    pptremoter2val = Column(String, nullable=False, comments=None)
    # Rep 2: (double entry)
    # Field Type: text
    # Choices: N/A
    pptremoter2val_d = Column(String, nullable=False, comments=None)
    # Rep 2 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_rep8 = Column(String, nullable=False, comments=None)
    # Rep 3
    # Field Type: text
    # Choices: N/A
    pptremoter3val = Column(String, nullable=False, comments=None)
    # Rep 3: (double entry)
    # Field Type: text
    # Choices: N/A
    pptremoter3val_d = Column(String, nullable=False, comments=None)
    # Rep 3 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_rep9 = Column(String, nullable=False, comments=None)
    # Dynamic Mechanical Allodynia (DMA): (double entry of data to ...
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_1 = Column(String, nullable=False, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_2 = Column(String, nullable=False, comments=None)
    # Rep 1
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmacontr1pain = Column(Numeric, nullable=False, comments=None)
    # Rep 1: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmacontr1pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 1 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_ctrl1 = Column(String, nullable=False, comments=None)
    # Rep 2
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmacontr2pain = Column(Numeric, nullable=False, comments=None)
    # Rep 2: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmacontr2pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 2 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_ctrl2 = Column(String, nullable=False, comments=None)
    # Rep 3
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmacontr3pain = Column(Numeric, nullable=False, comments=None)
    # Rep 3: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmacontr3pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 3 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_ctrl3 = Column(String, nullable=False, comments=None)
    # Rep 4
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmacontr4pain = Column(Numeric, nullable=False, comments=None)
    # Rep 4: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmacontr4pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 4 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_ctrl4 = Column(String, nullable=False, comments=None)
    # Rep 5
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmacontr5pain = Column(Numeric, nullable=False, comments=None)
    # Rep 5: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmacontr5pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 5 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_ctrl5 = Column(String, nullable=False, comments=None)
    # Index side (surgical)
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_3 = Column(String, nullable=False, comments=None)
    # Rep 1
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaindxr1pain = Column(Numeric, nullable=False, comments=None)
    # Rep 1: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaindxr1pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 1 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index1 = Column(String, nullable=False, comments=None)
    # Rep 2
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaindxr2pain = Column(Numeric, nullable=False, comments=None)
    # Rep 2: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaindxr2pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 2 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index2 = Column(String, nullable=False, comments=None)
    # Rep 3
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaindxr3pain = Column(Numeric, nullable=False, comments=None)
    # Rep 3: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaindxr3pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 3 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index3 = Column(String, nullable=False, comments=None)
    # Rep 4
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaindxr4pain = Column(Numeric, nullable=False, comments=None)
    # Rep 4: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaindxr4pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 4 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index4 = Column(String, nullable=False, comments=None)
    # Rep 5
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaindxr5pain = Column(Numeric, nullable=False, comments=None)
    # Rep 5: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaindxr5pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 5 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index5 = Column(String, nullable=False, comments=None)
    # Sensation comparison standardized site
    # Field Type: dropdown
    # Choices: 1, Equal on both sides | 2, Stronger on the surgery side | 3, Stronger on contralateral side
    dmasenscompare = Column(Integer, nullable=False, comments=None)
    # Patient specific site: DMA Pain ratings – Patient specific si...
    # Field Type: descriptive
    # Choices: N/A
    dma_ps_dt_1 = Column(String, nullable=False, comments=None)
    # Rep 1
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptcontr1pain = Column(Numeric, nullable=False, comments=None)
    # Rep 1: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptcontr1pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 1 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index6 = Column(String, nullable=False, comments=None)
    # Rep 2
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptcontr2pain = Column(Numeric, nullable=False, comments=None)
    # Rep 2: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptcontr2pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 2 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index7 = Column(String, nullable=False, comments=None)
    # Rep 3
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptcontr3pain = Column(Numeric, nullable=False, comments=None)
    # Rep 3: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptcontr3pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 3 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index8 = Column(String, nullable=False, comments=None)
    # Rep 4
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptcontr4pain = Column(Numeric, nullable=False, comments=None)
    # Rep 4: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptcontr4pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 4 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index9 = Column(String, nullable=False, comments=None)
    # Rep 5
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptcontr5pain = Column(Numeric, nullable=False, comments=None)
    # Rep 5: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptcontr5pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 5 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index10 = Column(String, nullable=False, comments=None)
    # Index side (surgery)
    # Field Type: descriptive
    # Choices: N/A
    dma_ps_dt_2 = Column(String, nullable=False, comments=None)
    # Rep 1
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptindxr1pain = Column(Numeric, nullable=False, comments=None)
    # Rep 1: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptindxr1pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 1 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index11 = Column(String, nullable=False, comments=None)
    # Rep 2
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptindxr2pain = Column(Numeric, nullable=False, comments=None)
    # Rep 2: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptindxr2pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 2 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index12 = Column(String, nullable=False, comments=None)
    # Rep 3
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptindxr3pain = Column(Numeric, nullable=False, comments=None)
    # Rep 3: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptindxr3pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 3 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index13 = Column(String, nullable=False, comments=None)
    # Rep 4
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptindxr4pain = Column(Numeric, nullable=False, comments=None)
    # Rep 4: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptindxr4pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 4 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index14 = Column(String, nullable=False, comments=None)
    # Rep 5
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptindxr5pain = Column(Numeric, nullable=False, comments=None)
    # Rep 5: (double entry)
    # Field Type: dropdown
    # Choices: 0.0, 0.0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10.0, 10.0
    dmaptindxr5pain_d = Column(Numeric, nullable=False, comments=None)
    # Rep 5 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    dma_dt_index15 = Column(String, nullable=False, comments=None)
    # Patient-Specific site assessed?
    # Field Type: radio
    # Choices: 1, 1. No, no new pain site or < 4 cm from standardized site | 2, 2. Yes, tested pt-specific site
    dmaptspecsite = Column(Integer, nullable=False, comments=None)
    # Sensation comparison patient-specific site
    # Field Type: radio
    # Choices: 1, 1. Equal on both sides | 2, 2. Stronger on surgery side | 3, 3. Stronger on contralateral side
    dmaptsenscompare = Column(Integer, nullable=False, comments=None)
    # DMA Test(s) completed
    # Field Type: radio
    # Choices: 1, Yes, all 4 sites | 2, Yes, but only some sites | 0, None
    dmatestcompyn = Column(Integer, nullable=False, comments=None)
    # Choose all completed sites
    # Field Type: checkbox
    # Choices: 1, 1. Standardized control site (contralateral) | 2, 2. Standardized index site (surgical) | 3, 3. Patient specific control site (contralateral) | 4, 4. Patient specific index site (surgical)
    dmatestcompwhich = Column(Integer, nullable=False, comments=None)
    # Rep 1
    # Field Type: text
    # Choices: N/A
    pptindxr1val = Column(String, nullable=False, comments=None)
    # Rep 1: (double entry)
    # Field Type: text
    # Choices: N/A
    pptindxr1val_d = Column(String, nullable=False, comments=None)
    # Rep 1 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_irep4 = Column(String, nullable=False, comments=None)
    # Rep 2
    # Field Type: text
    # Choices: N/A
    pptindxr2val = Column(String, nullable=False, comments=None)
    # Rep 2: (double entry)
    # Field Type: text
    # Choices: N/A
    pptindxr2val_d = Column(String, nullable=False, comments=None)
    # Rep 2 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_irep5 = Column(String, nullable=False, comments=None)
    # Rep 3
    # Field Type: text
    # Choices: N/A
    pptindxr3val = Column(String, nullable=False, comments=None)
    # Rep 3: (double entry)
    # Field Type: text
    # Choices: N/A
    pptindxr3val_d = Column(String, nullable=False, comments=None)
    # Rep 3 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_irep6 = Column(String, nullable=False, comments=None)
    # Initial Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsremoter1initial = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsremoter1initial_d = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsremoter1final = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsremoter1final_d = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsremoter2initial = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsremoter2initial_d = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsremoter2final = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsremoter2final_d = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsremoter3initial = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsremoter3initial_d = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating entries do not match! Please check your e...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_index_ipr_3 = Column(String, nullable=False, comments=None)
    # Final Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsremoter3final = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsremoter3final_d = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating entries do not match! Please check your ent...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_index_fpr_7 = Column(String, nullable=False, comments=None)
    # Remote After-sensations
    # Field Type: descriptive
    # Choices: N/A
    tsremote_dt_1 = Column(String, nullable=False, comments=None)
    # 7. 15 sec
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsremoteafter15 = Column(Numeric, nullable=False, comments=None)
    # 8. 30 sec
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsfinalpainremafts31 = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxr1initial = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxr1initial_d = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxr1final = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxr1final_d = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxr2initial = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxr2initial_d = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating entries do not match! Please check your e...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_index_fpr_3 = Column(String, nullable=False, comments=None)
    # Final Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxr2final = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxr2final_d = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating entries do not match! Please check your ent...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_index_fpr_4 = Column(String, nullable=False, comments=None)
    # Initial Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxr3initial = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxr3initial_d = Column(Numeric, nullable=False, comments=None)
    # Initial Pain Rating entries do not match! Please check your e...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_index_fpr_5 = Column(String, nullable=False, comments=None)
    # Final Pain Rating
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxr3final = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxr3final_d = Column(Numeric, nullable=False, comments=None)
    # Final Pain Rating entries do not match! Please check your ent...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_index_fpr_6 = Column(String, nullable=False, comments=None)
    # Index After-sensations
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_15 = Column(String, nullable=False, comments=None)
    # 15. 15 sec
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxafter15 = Column(Numeric, nullable=False, comments=None)
    # 16. 30 sec
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    tsindxafter30 = Column(Numeric, nullable=False, comments=None)
    # Confirm water temp 10 deg C (+/-1 deg)
    # Field Type: radio
    # Choices: 1, Yes | 0, No
    cpmcoldwatertemp = Column(Boolean, nullable=False, comments=None)
    # Cold Water Pain Rating at 30 sec
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    cpmcoldwaterpain30 = Column(Numeric, nullable=False, comments=None)
    # Cold Water Pain Rating at 30 sec: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    cpmcoldwaterpain30_d = Column(Numeric, nullable=False, comments=None)
    # Cold water pain at 30 seconds entries do not match! Please ch...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_cpm_1 = Column(String, nullable=False, comments=None)
    # Cold Water Pain Rating at 60 sec
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    cpmcoldwaterpain60 = Column(Numeric, nullable=False, comments=None)
    # Cold Water Pain Rating at 60 sec: (double entry)
    # Field Type: dropdown
    # Choices: 0, 0 | 0.5, 0.5 | 1.0, 1.0 | 1.5, 1.5 | 2.0, 2.0 | 2.5, 2.5 | 3.0, 3.0 | 3.5, 3.5 | 4.0, 4.0 | 4.5, 4.5 | 5.0, 5.0 | 5.5, 5.5 | 6.0, 6.0 | 6.5, 6.5 | 7.0, 7.0 | 7.5, 7.5 | 8.0, 8.0 | 8.5, 8.5 | 9.0, 9.0 | 9.5, 9.5 | 10, 10
    cpmcoldwaterpain60_d = Column(Numeric, nullable=False, comments=None)
    # Cold water pain at 60 seconds entries do not match! Please ch...
    # Field Type: descriptive
    # Choices: N/A
    ts_dt_cpm_2 = Column(String, nullable=False, comments=None)
    # Rep 1
    # Field Type: text
    # Choices: N/A
    cpmpptremr1val = Column(String, nullable=False, comments=None)
    # Rep 1: (double entry)
    # Field Type: text
    # Choices: N/A
    cpmpptremr1val_d = Column(String, nullable=False, comments=None)
    # Rep 1 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_rep4 = Column(String, nullable=False, comments=None)
    # Rep 2
    # Field Type: text
    # Choices: N/A
    cpmpptremr2val = Column(String, nullable=False, comments=None)
    # Rep 2: (double entry)
    # Field Type: text
    # Choices: N/A
    cpmpptremr2val_d = Column(String, nullable=False, comments=None)
    # Rep 2 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_rep5 = Column(String, nullable=False, comments=None)
    # Rep 3
    # Field Type: text
    # Choices: N/A
    cpmpptremr3val = Column(String, nullable=False, comments=None)
    # Rep 3: (double entry)
    # Field Type: text
    # Choices: N/A
    cpmpptremr3val_d = Column(String, nullable=False, comments=None)
    # Rep 3 entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    ppt_dt_rep6 = Column(String, nullable=False, comments=None)
    # Cuff pressure contraindicated
    # Field Type: radio
    # Choices: 1, Yes | 0, No
    cuffpfmricontraindyn = Column(Boolean, nullable=False, comments=None)
    # Which leg is non-dominant?
    # Field Type: radio
    # Choices: 1, Right | 2, Left
    cuffpfmrinondomleg = Column(Integer, nullable=False, comments=None)
    # Ignored multiline Field Name in Data Dictionary
    # Field Type: descriptive
    # Choices: N/A
    cuff_dt_1 = Column(String, nullable=False, comments=None)
    # Calf of non-dominant leg pressure
    # Field Type: text
    # Choices: N/A
    cuffpfmripressure = Column(String, nullable=False, comments=None)
    # Calf of non-dominant leg pressure 1: (double entry)
    # Field Type: text
    # Choices: N/A
    cuffpfmripressure_d = Column(String, nullable=False, comments=None)
    # Cuff pressure entries do not match! Please check your entries.
    # Field Type: descriptive
    # Choices: N/A
    fmricuff_dt_1 = Column(String, nullable=False, comments=None)
